// <auto-generated />
namespace firstdemonewmvcasp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class added_Membershiptype_foreignkey_in_customers_tbl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_Membershiptype_foreignkey_in_customers_tbl));
        
        string IMigrationMetadata.Id
        {
            get { return "202304111800588_added_Membershiptype_foreignkey_in_customers_tbl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
