-- CREATE PROCEDURE
DELIMITER $$
CREATE PROCEDURE SPDEMOINFO()
BEGIN
SELECT Emp_Name, GENDER FROM personal;
END $$
DELIMITER ;
-- SELECT PROCEDURE
CALL SPDEMOINFO();
-- DROP PROCEDURE
DROP PROCEDURE GET_PAYMENT;
DROP PROCEDURE SPDEMO;

-- PARAMETER PROCEDURE
DELIMITER $$
CREATE PROCEDURE SPPARAMETER
(
  id INTEGER,
  gender VARCHAR(10) 
)
BEGIN
SELECT  * FROM personal pr
where pr.Emp_ID = id AND pr.GENDER = gender;
END $$
DELIMITER ;
CALL SPPARAMETER(3, 'M');

DROP PROCEDURE SPPARAMETER2;
DROP PROCEDURE SPPARAMETER1;
DROP PROCEDURE SPPARAMETER;
DROP PROCEDURE spvariabledemo;
DROP PROCEDURE spvariabledemo1;

-- variable 
DELIMITER $$
CREATE PROCEDURE spvariabledemo()
BEGIN
 DECLARE totalName varchar(10)  ;
SELECT  count(*) into totalName FROM personal;
SELECT totalName;
END $$
DELIMITER ;
CALL employee.spvariabledemo();


