USE [master]
GO

/****** Object:  Database [skila]    Script Date: 5/2/2023 4:56:54 PM ******/
CREATE DATABASE [skila]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'skila', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\skila.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'skila_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\skila_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [skila].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [skila] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [skila] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [skila] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [skila] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [skila] SET ARITHABORT OFF 
GO

ALTER DATABASE [skila] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [skila] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [skila] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [skila] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [skila] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [skila] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [skila] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [skila] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [skila] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [skila] SET  DISABLE_BROKER 
GO

ALTER DATABASE [skila] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [skila] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [skila] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [skila] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [skila] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [skila] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [skila] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [skila] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [skila] SET  MULTI_USER 
GO

ALTER DATABASE [skila] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [skila] SET DB_CHAINING OFF 
GO

ALTER DATABASE [skila] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [skila] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [skila] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [skila] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [skila] SET QUERY_STORE = ON
GO

ALTER DATABASE [skila] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [skila] SET  READ_WRITE 
GO

