// <auto-generated />
namespace Authentication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_table_MemberShipType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_table_MemberShipType));
        
        string IMigrationMetadata.Id
        {
            get { return "202304182051018_Add_table_MemberShipType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
