USE DEMO;
CREATE TABLE CITY(
  CID INT PRIMARY KEY,CNAME VARCHAR(255));
  INSERT INTO CITY VALUES (5,'NOIDA');
  CREATE TABLE STUDENT(
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255),PERCENTAGE INT,AGE INT ,GENDER VARCHAR(255),CITY INT,
  FOREIGN KEY(CITY) REFERENCES CITY (CID));
  SELECT * FROM CITY;
  INSERT INTO STUDENT VALUES(1,'RAM KUMAR',45,19,'M',1);
  INSERT INTO STUDENT VALUES(2,'SARITA KUMARI',55,22,'F',2);
  INSERT INTO STUDENT VALUES(3,'SALMAN KHAN',62,20,'M',1);
  INSERT INTO STUDENT VALUES(4,'JUHI CHAWLA',47,18,'F',3);
  INSERT INTO STUDENT VALUES(5,'ANIL KAPOOR',74,22,'M',1);
  INSERT INTO STUDENT VALUES(6,'JOHN ABRAHAM',64,21,'M',2);
  INSERT INTO STUDENT VALUES(7,'SHAHID KAPOOR',52,20,'M',1);
  SELECT * FROM STUDENT;
  SELECT S.ID,S.NAME,S.PERCENTAGE,S.AGE,S.GENDER,C.CNAME  FROM STUDENT S INNER JOIN CITY C ON  S.CITY = C.CID
  WHERE C.CNAME='AGRA'
  ORDER BY S.NAME;
  SELECT * FROM STUDENT RIGHT JOIN CITY 
  ON STUDENT.CITY = CITY.CID ;
  USE DEMO
   SELECT * FROM STUDENT CROSS JOIN CITY;  
   SELECT S.ID,S.NAME ,C.CNAME FROM STUDENT S , CITY C;
     SELECT S1.NAME , S2.CITY FROM STUDENT AS S1
        INNER JOIN STUDENT AS S2 ON
         S1.ID = S2.CITY;
          SELECT * FROM STUDENT AS S1
        INNER JOIN STUDENT AS S2 ON
         S1.ID = S2.CITY;
         
         
          SELECT * FROM STUDENT;
          
         SELECT S1.NAME AS CITY  ,S2.NAME AS ID 
          FROM STUDENT AS S1 
          INNER JOIN STUDENT AS S2 
          ON S1.ID = S2.CITY;
          
          
          SELECT * FROM STUDENT CROSS JOIN CITY;  
          
          CREATE TABLE COURSE
( CRID INT PRIMARY KEY,
  COURSE VARCHAR(255));
  INSERT INTO COURSE VALUES(1,'BTECH');
  INSERT INTO COURSE VALUES(2,'BCA');
   INSERT INTO COURSE VALUES(3,'BBA');
   SELECT * FROM COURSE;
   SELECT * FROM STUDENT 
          INNER JOIN CITY ON  
           STUDENT.ID = CITY.CID
            INNER JOIN COURSE
            STUDENT.ID = COURSE.CRID;
              SELECT * FROM STUDENT 
          INNER JOIN CITY ON  
           STUDENT.CITY = CITY.CID
            INNER JOIN COURSE
            STUDENT.ID = COURSE.CRID;
            SELECT S.ID,S.NAME,S.AGE,S.GENDER , C.CNAME , C1.COURSE FROM STUDENT S 
          INNER JOIN CITY C  ON  
           S.CITY = C.CID
            INNER JOIN COURSE C1 ON
            S.COURSE = C1.CRID;		
            ALTER TABLE STUDENT ADD COLUMN COURSE INT;
            UPDATE STUDENT SET  COURSE = 3 WHERE ID =7;
            
            USE WORLD;
            SELECT * FROM CUSTOMER;
            SELECT * FROM ORDER1;
            
            
        SELECT * FROM PAYMENT P JOIN
		 RENTAL R ON 
		 P.STAFF_ID = R.STAFF_ID
		 AND P.RENTAL_ID = R.RENTAL_ID;
          SELECT * FROM STUDENT JOIN CITY WHERE STUDENT.ID = CITY.CID;
            SELECT * FROM STUDENT , CITY   WHERE STUDENT.ID = CITY.CID;
            
		(SELECT *
            FROM CUSTOMER 
          left OUTER JOIN ORDER1 o1 ON CUSTOMER.ID = o1.ID 
        ORDER BY CUSTOMER.NAME;	)
        
       ( SELECT *
            FROM CUSTOMER 
          left OUTER JOIN ORDER1 o1 ON CUSTOMER.ID = o1.ID 
        ORDER BY CUSTOMER.NAME;	)
        SELECT * FROM CUSTOMER JOIN ORDER1  USING(ID);
        SELECT * FROM CUSTOMER NATURAL JOIN ORDER1;
        CREATE TABLE LECTURERS(
     ID INT ,NAME VARCHAR(255),
	 AGE INT,GENDER VARCHAR(10),
	 CITY INT,COURSE INT);
     INSERT INTO LECTURERS VALUES (1,'RAJ KAPOOR',37,'M',1,2);
     DROP TABLE LECTURERS;
     	 INSERT INTO LECTURERS VALUES (2,'SADHANA',39,'F',4,3);
	 INSERT INTO LECTURERS VALUES (3,'RAM KUMAR',38,'M',2,1);
	 INSERT INTO LECTURERS VALUES (4,'SALIM KHAN',45,'M',3,2);
	 INSERT INTO LECTURERS VALUES (5,'NAGMA',42,'F',2,1);
     SELECT * FROM STUDENT
	 UNION
	  SELECT * FROM LECTURERS;