SELECT * FROM demo.city;
select round(5.79);   -- ROUND INTEGER NUMBER
select round(5.79,1);
select truncate(5.79584,2);
SELECT ceiling(5.2);      -- //INCREMENT ANY NUMBER
SELECT FLOOR(5.8);      -- ALWAYS DECREASE ROUND NUMBER
SELECT ABS(-5.8);-- NEGATIVE TO POSITIVE VALUE
SELECT RAND();-- ANY RANDOM NUMBER
-- STRING    
SELECT LENGTH('BLUE');     4
SELECT LOWER('BLUE');  
SELECT UPPER('blue');
SELECT LTRIM('    BLUE');  -- left trim whitespace deleted
SELECT RTRIM('BLUE    '); --   RIGHT TRIM DELETED WHITESPACE
SELECT LEFT('BLUEWHEAL',4);  --  COUNT 4 WORLD RETURN LEFT SIDE
SELECT RIGHT('BLUEWHEAL',5);  --  COUNT 5 WORD FOR RIGHT SIDE
SELECT SUBSTRING('HELLOGOOD',3);   -- START WITH 3 TO WHOLE WORD
SELECT SUBSTRING('HELLOGOOD',3,6);  -- START WITH 3 END WITH 6
SELECT LOCATE ('O','HELLOGOOD');   -- FIND O WITH  FIRST POSITION
select LOCATE('GOOD','HELLOGOOD');   -- WHOLE STRING SEARCH ALSO
SELECT REPLACE('HELLOGOOD','GOOD','GOD'); -- //REPLACE WORD
select concat('good','morning');  -- concat good morning


