USE WORLD;
SELECT * FROM CUSTOMER;

DELIMITER $$
CREATE TRIGGER PAYMENT_AFTER_INSERT
  AFTER INSERT ON CUSTOMER
  FOR EACH ROW
BEGIN
  UPDATE ORDER1
  SET PRICE = PRICE + NEW.PRICE
  WHERE ORDER1.ID = NEW.ORDER1.ID;
END $$
DELIMITER ;  
INSERT INTO CUSTOMER VALUES(2,'JACK',2002-06-10,9362410250,'SURAT',80000);


CREATE trigger SALARY
BEFORE INSERT OR DELETE OR UPDATE ON CUSTOMER
FOR EACH ROW
DECLARE SALARY;
BEGIN
SALARY = NEW.PRICE - OLD.PRICE;
END;
ROLLBACK;
  
  USE DEMO;
  CREATE TABLE EMP(
  ID INT,
  NAME VARCHAR(30),
  SAL DECIMAL(10,2)
  )
  
  USE DEMO;
  INSERT INTO EMP VALUES(1,'ANAND',15000);
  INSERT INTO EMP VALUES (2,'NEHA',12400);
  INSERT INTO EMP VALUES(3,'SOHAN',11500);
  INSERT INTO EMP VALUES('VIJAY',15500);
  INSERT INTO EMP VALUES(5,'SAPNA',14000);
  SELECT * FROM EMP;
  CREATE TABLE EMP1(
  ID INT,
  NAME VARCHAR(30),
  SAL DECIMAL(10,2)
  )
  TRUNCATE TABLE EMP1;