//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX_Designer
{
    using System;
    
    public enum CoursLevel : byte
    {
        Beginner = 1,
        intermediate = 2,
        Advance = 3
    }
}
