-- COMMIT
START TRANSACTION;
DELETE FROM personal;
ROLLBACK;

SELECT * FROM personal;
-- ROLLBACK
START TRANSACTION;
DELETE FROM personal;
COMMIT;

SELECT * FROM personal;

-- MULTIPLE QUERY
START TRANSACTION;
INSERT INTO PERSONAL VALUES (0006, 'DINESH', 54, 95, 'F', 4, 2);
UPDATE PERSONAL SET Emp_Name = 'RIYA' WHERE Emp_ID = 3;
DELETE FROM personal WHERE Emp_ID = 5;
COMMIT;
START TRANSACTION;
INSERT INTO PERSONAL VALUES (0007, 'PARESH', 14, 95, 'F', 2, 1);
UPDATE PERSONAL SET AGE = '23' WHERE Emp_ID = 3;
DELETE FROM personal WHERE Emp_ID = 6;
ROLLBACK;













;
