-- VIEW 
CREATE VIEW PERSONALDATA
AS
SELECT Emp_ID , Emp_Name, COUR_NAME
FROM personal PR
INNER JOIN courses CO
ON PR.COURSES = CO.COUR_ID;

-- ALTER VIEW
ALTER VIEW PERSONALDATA
AS
SELECT Emp_ID , Emp_Name, COUR_NAME, C_Name
FROM personal PR
INNER JOIN courses CO
ON PR.COURSES = CO.COUR_ID
INNER JOIN city CI
ON PR.CITY = CI.C_ID ;

SELECT * FROM PERSONALDATA;

-- RENAME VIEW NAME
RENAME TABLE PERSONALDATA
TO PERSONALDATAINFO;

-- DELETE(DROP) VIEW
USE EMPLOYEE;
DROP VIEW PERSONALDATA;

-- INSERT VIEW
CREATE VIEW INVIEWDEMO
AS 
SELECT * FROM selfjoin;
SELECT * FROM INVIEWDEMO;

-- UPDATE VIEW
UPDATE INVIEWDEMO
SET Emp_Name = 'DIPALI'
WHERE Emp_ID = 6;

-- DELETE VIEW
DELETE FROM INVIEWDEMO
WHERE Emp_ID = 6;

INSERT INTO INVIEWDEMO VALUES (6, 'DIPIKA', 3);