SELECT * FROM world.customer;

CREATE DATABASE SQLSTORE;
USE SQLSTORE;
CREATE TABLE CUSTOMER
(
 CUSTOMER_ID INT PRIMARY KEY  AUTO_INCREMENT,
 FIRST_NAME VARCHAR(50) NOT NULL,
 POINTS INT NOT NULL DEFAULT 0,
 EMAIL VARCHAR(255) NOT NULL UNIQUE
 );
 
 
 ALTER table CUSTOMER
 ADD LAST_NAME VARCHAR(50) NOT NULL
 AFTER FIRST_NAME;
 ALTER TABLE CUSTOMER
 ADD CITY  VARCHAR(50) NOT NULL,
 MODIFY COLUMN FIRST_NAME VARCHAR(55) DEFAULT '',
 DROP POINTS;
 DESC CUSTOMER;
 DROP TABLE IF EXISTS ORDERS;
 CREATE TABLE ORDERS (
 ORDER_ID INT  PRIMARY KEY NOT NULL,
 CUSTOMER_ID INT NOT NULL,
 FOREIGN KEY FK_ORDER_CUSTOMER(CUSTOMER_ID)
 REFERENCES CUSTOMER (CUSTOMER_ID)
 ON UPDATE CASCADE
 ON DELETE NO ACTION);
 
 
 ALTER TABLE ORDERS
 ADD PRIMARY KEY(ORDER_ID),
 DROP PRIMARY KEY,
 DROP FOREIGN KEY FK_ORDERS_CUSTOMER,
 ADD FOREIGN KEY FK_ORDERS_CUSTOMER (CUSTOMER_ID)
 REFERENCES CUSTOMER (CUSTOMER_ID)
 ON UPDATE CASCADE
 ON DELETE NO ACTION;
 
 
 SHOW CHARSET;