   SELECT * FROM demo.city;
select round(5.79);   -- ROUND INTEGER NUMBER
select round(5.79,1);
select truncate(5.79584,2);
SELECT ceiling(5.2);      -- //INCREMENT ANY NUMBER
SELECT FLOOR(5.8);      -- ALWAYS DECREASE ROUND NUMBER
SELECT ABS(-5.8);-- NEGATIVE TO POSITIVE VALUE
SELECT RAND();-- ANY RANDOM NUMBER
-- STRING    
SELECT LENGTH('BLUE');     4
SELECT LOWER('BLUE');  
SELECT UPPER('blue');
SELECT LTRIM('    BLUE');  -- left trim whitespace deleted
SELECT RTRIM('BLUE    '); --   RIGHT TRIM DELETED WHITESPACE
SELECT LEFT('BLUEWHEAL',4);  --  COUNT 4 WORLD RETURN LEFT SIDE
SELECT RIGHT('BLUEWHEAL',5);  --  COUNT 5 WORD FOR RIGHT SIDE
SELECT SUBSTRING('HELLOGOOD',3);   -- START WITH 3 TO WHOLE WORD
SELECT SUBSTRING('HELLOGOOD',3,6);  -- START WITH 3 END WITH 6
SELECT LOCATE ('O','HELLOGOOD');   -- FIND O WITH  FIRST POSITION
select LOCATE('GOOD','HELLOGOOD');   -- WHOLE STRING SEARCH ALSO
SELECT REPLACE('HELLOGOOD','GOOD','GOD'); -- //REPLACE WORD
select concat('good','morning');  -- concat good morning


-- DATE FUNCTION
SELECT NOW();
SELECT CURDATE();
SELECT CURTIME();
SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT YEAR(NOW());
SELECT DAY(NOW());
SELECT MONTHNAME(NOW());  
SELECT EXTRACT(MONTH FROM NOW());
SELECT EXTRACT(YEAR FROM NOW());
SELECT DATE_FORMAT(NOW(),'%m %d %y');
SELECT DATE_FORMAT(NOW(),'%M %d %Y');
SELECT DATE_ADD(NOW(),INTERVAL 1 DAY);
SELECT DATE_ADD(NOW(),INTERVAL 1 YEAR);
SELECT DATE_ADD(NOW(),INTERVAL -1 DAY);
SELECT DATE_ADD(NOW(),INTERVAL -1 YEAR);
SELECT DATEDIFF('2019-01-05' , '2019-01-01');
SELECT TIME_TO_SEC('09:02')-TIME_TO_SEC('09:00');


SELECT * FROM world.customer;
USE WORLD;
SELECT ID,NAME ,IFNULL(PHONE,'NOT ASSIGNED') AS NUMBER FROM CUSTOMER;

USE DEMO;
SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM CITY;
ALTER VIEW STUDENTDATA
AS 
SELECT S.ID,S.NAME,C.COURSE,C1.CNAME FROM
STUDENT S 
INNER JOIN COURSE C
ON S.COURSE = C.CRID
INNER JOIN CITY C1
ON S.CITY = C1.CID;

SELECT * FROM STUDENTDATA;

USE WORLD;
SELECT * FROM CUSTOMER;

CREATE OR REPLACE VIEW CUST1 AS
SELECT ID,NAME,BIRTHDATE,ADDRESS,EMAIL,
PRICE - 100 AS BALANCE,
PHONE 
FROM CUSTOMER;
SELECT * FROM CUST1;

DELETE FROM CUST1
WHERE ID = 9;
update cust1 
set birthdate=date_add(birthdate,interval 2 day)
where id=1;