SELECT * FROM world.country;

SELECT COUNT(*) FROM COUNTRY;
CREATE INDEX IDX_CON ON COUNTRY(CONTINENT);
EXPLAIN SELECT CODE,NAME FROM COUNTRY WHERE INDEPYEAR > 1000;
CREATE INDEX IDX_IN ON COUNTRY(INDEPYEAR);
DROP INDEX IDX_IN ON COUNTRY;
DROP INDEX  IDX_CON ON COUNTRY;

SHOW INDEXES IN COUNTRY;
ANALYZE TABLE COUNTRY;


CREATE INDEX IDX_NAME ON COUNTRY (NAME(10));

SELECT 
COUNT(DISTINCT LEFT (NAME,1)),COUNT(DISTINCT LEFT (NAME,5)) FROM COUNTRY;
USE DEMO;
CREATE FULLTEXT INDEX IDX_TIBIO ON PASSENGER(NAME,ADDRESS);
SELECT * ,MATCH(NAME,ADDRESS) AGAINST ('RA MA')
 FROM PASSENGER  
WHERE MATCH(NAME,ADDRESS) AGAINST ('RA MA' in boolean mode);
SELECT * ,MATCH(NAME,ADDRESS) AGAINST ('rahul')
 FROM PASSENGER 
WHERE MATCH(NAME,ADDRESS) AGAINST ('rahul' in boolean mode);

CREATE INDEX IDX_NAME_CHARGE ON PASSENGER (NAME,CHARGES);
EXPLAIN SELECT ID FROM PASSENGER
WHERE NAME LIKE 'R%' AND CHARGES > 2000;

SHOW INDEX FROM  PASSENGER;
SHOW INDEX IN PASSENGER;
USE WORLD;
SELECT 
COUNT(DISTINCT NAME),
COUNT(DISTINCT BIRTHDATE)
FROM CUSTOMER;
EXPLAIN SELECT ID FROM CUSTOMER 
WHERE NAME = 'HINA' AND BIRTHDATE = 2002-11-11;
CREATE INDEX IDX_NAME_BI  ON customer (NAME,BIRTHDATE);
DROP INDEX IDX_NAME_BI ON customer;
EXPLAIN SELECT ID FROM CUSTOMER 
WHERE BIRTHDATE = 2002-11-11 AND NAME = 'HINA'  ;
CREATE INDEX IDX_NAME_BI  ON customer (BIRTHDATE,NAME);

EXPLAIN 
SELECT ID FROM CUSTOMER
WHERE  NAME='HINA'
UNION
SELECT ID FROM CUSTOMER
WHERE BIRTHDATE >=   2002-11-11;