USE DEMO;
CREATE TABLE CITY(
  CID INT PRIMARY KEY,CNAME VARCHAR(255));
  INSERT INTO CITY VALUES (5,'NOIDA');
  CREATE TABLE STUDENT(
  ID INT PRIMARY KEY NOT NULL,
  NAME VARCHAR(255),PERCENTAGE INT,AGE INT ,GENDER VARCHAR(255),CITY INT,
  FOREIGN KEY(CITY) REFERENCES CITY (CID));
  SELECT * FROM CITY;
  INSERT INTO STUDENT VALUES(1,'RAM KUMAR',45,19,'M',1);
  INSERT INTO STUDENT VALUES(2,'SARITA KUMARI',55,22,'F',2);
  INSERT INTO STUDENT VALUES(3,'SALMAN KHAN',62,20,'M',1);
  INSERT INTO STUDENT VALUES(4,'JUHI CHAWLA',47,18,'F',3);
  INSERT INTO STUDENT VALUES(5,'ANIL KAPOOR',74,22,'M',1);
  INSERT INTO STUDENT VALUES(6,'JOHN ABRAHAM',64,21,'M',2);
  INSERT INTO STUDENT VALUES(7,'SHAHID KAPOOR',52,20,'M',1);
  SELECT * FROM STUDENT;
  SELECT S.ID,S.NAME,S.PERCENTAGE,S.AGE,S.GENDER,C.CNAME  FROM STUDENT S INNER JOIN CITY C ON  S.CITY = C.CID
  WHERE C.CNAME='AGRA'
  ORDER BY S.NAME;
  SELECT * FROM STUDENT RIGHT JOIN CITY 
  ON STUDENT.CITY = CITY.CID ;
  